spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 6d1947a3ab6d8c4a6189
            clientSecret: dd503d32db73b1157a49e7c08f28feef5c6bd34f
          google:
            clientId: 1091128367767-5do1gle598oi4l6jaf5ckqtdi0vkdcje.apps.googleusercontent.com
            clientSecret: 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
